---
- src: geerlingguy.ntp
- src: geerlingguy.php-versions
- src: geerlingguy.php
- src: geerlingguy.composer
- src: geerlingguy.apache
- src: geerlingguy.apache-php-fpm
- src: geerlingguy.mysql
- src: geerlingguy.supervisor
